# Generated by Django 5.2.4 on 2026-06-22 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_fix_patient_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number format is invalid.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
